### ISSUE TITLE
setup for python3 should use pyvenv instead of virtualenv?

### ISSUE THREAD

**Issue by milohax** [sinewalker/sinewalker.github.io#13]
Apparently this is a thing in Python3?

Mentioned in "[How to Make Mistakes in Python](http://www.oreilly.com/programming/free/how-to-make-mistakes-in-python.csp?intcmp=il-prog-free-product-lgen_python_mistakes)" by [Mike Pirnat](http://www.oreilly.com/pub/au/6543).

I should verify this, and then update the wiki if it's true.

**Comment by sinewalker** [comment]
hey look at that:  i'm talking to myself.

**Comment by sinewalker** [comment]
This [Stack Overflow Question](https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe) discusses the various python environment things.  The Accepted (and so far *only*) Answer mentions that [pyvenv was deprecated in Python 3.6](https://docs.python.org/dev/whatsnew/3.6.html#id8) anyway.

So that *may* answer this Question too....

**Comment by sinewalker** [comment]
Going by [the documentation](https://docs.python.org/3/library/venv.html) it's a bit unclear to me whether `python3 -m venv myenv path/to/myenv` has any advantage over virtualenv other than it is installed by default with Python 3.6+.  The Deprication of *pyvenv* and its relation to venv is pretty confusing.

Since I have clear instructions for using virtualenv, and the opininon of the SO answer is that the consesnus seems to be to still use virtualenv anyway. I'm closing this Quesiton with the Answer:

**just use virtualenv and ignore the advice about pyvenv**
